arith_set:
	python converter.py arithmetic_instructions.txt ../Instructions.hex

jb_set:
	python converter.py j_b_instructions.txt ../Instructions.hex

ls_set:
	python converter.py store_load_instructions.txt ../Instructions.hex

mixed_set:
	python converter.py mixed_instructions.txt ../Instructions.hex